## Ensimmäinen harjoitustehtävä - Ville Kurikka

Aloitetaan lataamalla tarvittavat importit. Osa pip-installilla, koska uusi environment

In [4]:
import keras

from keras.models import Sequential
from keras.layers import Input, Dense, Flatten
from keras.datasets import mnist
from keras.utils import to_categorical

In [ ]:
# pip install ucimlrepo

   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
   --------------------------------- ------ 9.4/11.3 MB 97.6 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 71.1 MB/s  0:00:00

   ---------------------------------------- 0/4 [pytz]
   ---------- ----------------------------- 1/4 [tzdata]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------------- 2/4 [pandas]
   -------------------- ------------

In [6]:
from ucimlrepo import fetch_ucirepo 

import pandas as pd
  
# fetch dataset 
iris = fetch_ucirepo(id=53) 
  
# data (as pandas dataframes) 
X = iris.data.features 
y = iris.data.targets 
  
# metadata 
print(iris.metadata) 
  
# variable information 
print(iris.variables) 

print(y.dtypes)

{'uci_id': 53, 'name': 'Iris', 'repository_url': 'https://archive.ics.uci.edu/dataset/53/iris', 'data_url': 'https://archive.ics.uci.edu/static/public/53/data.csv', 'abstract': 'A small classic dataset from Fisher, 1936. One of the earliest known datasets used for evaluating classification methods.\n', 'area': 'Biology', 'tasks': ['Classification'], 'characteristics': ['Tabular'], 'num_instances': 150, 'num_features': 4, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['class'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1936, 'last_updated': 'Tue Sep 12 2023', 'dataset_doi': '10.24432/C56C76', 'creators': ['R. A. Fisher'], 'intro_paper': {'ID': 191, 'type': 'NATIVE', 'title': 'The Iris data set: In search of the source of virginica', 'authors': 'A. Unwin, K. Kleinman', 'venue': 'Significance, 2021', 'year': 2021, 'journal': 'Significance, 2021', 'DOI': '1740-9713.01589', 'URL': 'https://www.semanticscholar.org

In [ ]:
# pip install scikit-learn

   ---------------------------------------- 0.0/8.9 MB ? eta -:--:--
   ---------------------------------------- 8.9/8.9 MB 79.2 MB/s  0:00:00
   ---------------------------------------- 0.0/38.7 MB ? eta -:--:--
   ----------------- ---------------------- 17.0/38.7 MB 89.7 MB/s eta 0:00:01
   --------------------------------- ------ 32.8/38.7 MB 83.3 MB/s eta 0:00:01
   ---------------------------------------- 38.7/38.7 MB 66.5 MB/s  0:00:00

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 

Muutetaan aluksi target labelit numeroiksi, ja tämän jälkeen categorical-dataksi

In [8]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

encoder = LabelEncoder()
y = encoder.fit_transform(y)




y = to_categorical(y, 3)




e:\Anaconda\envs\neurot\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
print(y)
print(X.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

Data näyttää oikeanmuotoiselta.

In [10]:
print(X.dtypes)

sepal length    float64
sepal width     float64
petal length    float64
petal width     float64
dtype: object


X-dataframessa voidaan hyödyntää float-arvoja, mutta skaalataan standardscalerilla. Tämä vaikutti parantavan tarkkuutta noin neljällä prosenttiyksiköllä.

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

Aloitetaan mallin rakennus. Alla siis 1 inputlayer, jossa 4 muuttujaa. Flattenia ei tarvita, koska 1d-dataa jo valmiiksi. Seuraavaksi 1 hidden layer, jossa 16 neuronia. Lopuksi vielä output-layer

In [12]:
model = Sequential([
    Input(shape=(4, )),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])

Hyödynnetään mallin rakennuksessa Adam-optimizeria. Muutetaan learning rate 0.001:stä 0.01:teen

In [13]:
opt = keras.optimizers.Adam(learning_rate=0.01)

model.compile(optimizer=opt,
loss='categorical_crossentropy',
metrics=['accuracy'])

Koulutetaan malli. Epookkeja 6 kpl, ja jokaisella kerralla jaetaan datasetti 5 batchiin. Jokaisesta batchista otetaan 20 % validointia varten.

In [14]:
model.fit(X, y, epochs=6, batch_size=5, validation_split=0.2)

Epoch 1/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.5000 - loss: 0.9160 - val_accuracy: 0.0667 - val_loss: 1.0197
Epoch 2/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9000 - loss: 0.5068 - val_accuracy: 0.0000e+00 - val_loss: 1.1603
Epoch 3/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8833 - loss: 0.3716 - val_accuracy: 0.0667 - val_loss: 0.8732
Epoch 4/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8750 - loss: 0.2952 - val_accuracy: 0.1333 - val_loss: 0.8829
Epoch 5/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8917 - loss: 0.2533 - val_accuracy: 1.0000 - val_loss: 0.3217
Epoch 6/6
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9083 - loss: 0.2445 - val_accuracy: 0.4667 - val_loss: 0.7378


In [15]:
test_loss, test_acc = model.evaluate(X, y)
print(test_acc)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8733 - loss: 0.2989 
0.8733333349227905


Mallin tarkkuus on n. 98,7 prosenttia.